name: CI Quality
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencias
        run: pip install -r requirements.txt
      - name: Run linter
        run: flake8 calculadora.py test_calculadora.py
      - name: Build (no aplica paara python)
        run: echo "build listo"
      - name: Run tests
        run: coverage run -m unittest test_calculadora.py
      - name: Report coverage
        run: coverage report
      - name: Check coverage >= 80%
        run: |
          COVERAGE=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
          if [ "$COVERAGE" -lt 80 ]; then
            echo "el coverage es muy bajo"
            exit 1
          fi
